//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chats
    {
        public long Id { get; set; }
        public long StudentId { get; set; }
        public long InstructorId { get; set; }
        public string Sender { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
    
        public virtual Instructors Instructors { get; set; }
        public virtual Students Students { get; set; }
    }
}
